### ISSUE TITLE
Create an OnSSET environment

### ISSUE THREAD

**Issue by NMoksnes** [OnSSET/onsset#111]
Create an environment with all python packages needed as onsset so that the user don't have to download each one individually.

**Comment by willu47** [comment]
You are able to `pip install onsset` install onsset.  However, this installs the code on your system as a package, so you don't have access to the code.

If you need to edit the code, you can still use pip to install it in `editable` more using `pip -e onsset`

**Comment by NMoksnes** [comment]
Ok. Great! So all the python packages that are needed to run onsset are in that installation?

**Comment by willu47** [comment]
They should be, yes.  When the tests run, this installation is also tested on [Travis CI](https://travis-ci.com/github/OnSSET/onsset).  If any of the dependencies break, then the tests will fail which gives us the signal to provide a fix.
