### ISSUE TITLE
Better way to move repo

### ISSUE THREAD

**Issue by carderne** [OnSSET/onsset#12]
Hi @AndreasSahlberg @akorkovelos,
Fully support cleaning up the repo and creating a 'canonical' version of OnSSET. However, by basing it on `gep-onsset` you've lost the 3.5 years of commit history in the `KTH-dESA/OnSSET` repo (and erased the contribution history from Dimitris, Babak and me).

It's relatively straight-forward to move the `KTH-dESA` version under the OnSSET organization, and then bring the new commits from `gep-onsset` across.

**Comment by willu47** [comment]
@AndreasSahlberg @carderne - We can merge (and I would encourage/support) in the earlier version of [OnSSET](/KTH-dESA/OnSSET-2016) to this repository, but this requires some care. I'd be happy to help out here, because it's a case we'll be potentially "rewriting history" from Git's perspective.

**Comment by willu47** [comment]
1. Transfer /KTH-DESA/OnSSET_2016 to /OnSSET/OnSSET_2016
2. Attempt to merge /OnSSET/OnSSET:master into /OnSSET/OnSSET_2016:master
3. [Force] Push new merged OnSSET history up to /OnSSET/OnSSET:master

**Comment by carderne** [comment]
Nice! Thanks both.

**Comment by willu47** [comment]
This has been completed. Please note below @akorkovelos @carderne @Dimitrismentis @babakkhavari @AndreasSahlberg 

ATTENTION! I have now “CLEANED” the onsset/onsset repository of files larger than 15MB. The reason for this is to reduce the size of the repository as a whole. This procedure removed 3 files as shown below:
Deleted files
- Afghanistan_Conflict.zip | 3546d974 (63.3 MB)                    
- Malawi.csv               | d7c4b907 (42.4 MB), 5068aa6e (42.4 MB)

This procedure updated the entire git history after the point in time that these large files were added.  The consequence of this is that ANY forks, clones or local copies of onsset are incompatible with the new version.  You should first make a local backup of your git repositories and then do the following:
1. Delete or remove your development copy of the onsset code.
2. `Git clone http://github.com/onsset/onsset`
3. Force push the new master branch to your existing forks by first setting up your remote (`git remote add <remote name> http://github.com/<username>/<onsset>` and then `git push -f master <remote name>/master`)
