### ISSUE TITLE
Separate gep-onsset or under "main" OnSSET?

### ISSUE THREAD

**Issue by akorkovelos** [OnSSET/onsset#2]
To be discussed in the [3rd OnSSET SteerCom](https://docs.google.com/document/d/1cfIGI8VTqe8thRDvkFTf0VfQIL7G79UOrVfICY-GaIk/edit#heading=h.8watytlsitlb) on June 19th in Trieste; For now gep-onsset is separate and based on the current circumstances will be maintained separately under GEP activities. Decision pending though..

**Comment by AndreasSahlberg** [comment]
OnSSET codebase now in OnSSET organisation, GEP version forked to global-electrification-platform organisation
