### ISSUE TITLE
Remove calculate_investments method, integrate directly in lcoe_calculation

### ISSUE THREAD

**Issue by AndreasSahlberg** [OnSSET/onsset#20]
Instead of first returning LCOE for each technology and then calculating the investment cost for the least-cost technology, always return the investment cost while returning the LCOE to improve speed and reduce number of methods. Will add additional rows to the results file.

Affects the following modules: get_lcoe, calculate_investments, grid_extension, calculate_off_grid_lcoes, results columns.

**Comment by oluchee** [comment]
calculate_investments and res_investments should be seperated as two different methods
