### ISSUE TITLE
condition_df misses columns

### ISSUE THREAD

**Issue by babakkhavari** [OnSSET/onsset#23]
The condition_df seems to miss columns. The columns processed in the function are GHI, Wind, NighttimeLights, Elevation, Slope, LandCover, SubstationsDist, RoadDist, HydropowerDist, Hydropower, ElecPop why not the rest?

The function would also potentially overwrite ElectrificationOrder with 0's if they had been included.

**Comment by AndreasSahlberg** [comment]
ElectrificationOrder is by default 0 before the analysis starts
