### ISSUE TITLE
calc_wind_cfs needed?

### ISSUE THREAD

**Issue by babakkhavari** [OnSSET/onsset#25]
We calculate the wind capacity factors in this method. The method assumes a measurement height for the wind speed. This is rather well hidden and easy to miss which might lead to there being errors in the windCF calculations.

There are also windCF and wind power density GIS layers readily available online and open, can we replace the functions with one of these layers directly from the extraction?

**Comment by AndreasSahlberg** [comment]
The hard-coded values should be broken out to avoid issues with hub height and wind measurement height etc.
