### ISSUE TITLE
Vectorize the get_lcoe function

### ISSUE THREAD

**Issue by AndreasSahlberg** [OnSSET/onsset#28]
By vectorizing the get_lcoe function to be able to calculate LCOEs for all settlement instead of iterating through the settlements the calculation speed of the tool can be significantly decrease. The get_lcoe function should still be made flexible to work with single settlements as well to function together with the elec_extension method.

**Comment by oluchee** [comment]
This method covers about 282 lines of code. Some of my additional suggestions include:
-The distribution network method can be seperated out of the get_lcoe method. 
-In the "new distribution network method", the HV/MV sizing and LV line sizing can be broken down into two methods 
-The get_lcoe method can further be broken down into one method that calculates the total_investment cost; and another that calculates the life-time.
